# Generated by Django 4.2.16 on 2024-10-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_accounttype_discount_orderstatus_paymenttype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="product",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="productbrand",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="deleted_at",
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/product/"
            ),
        ),
        migrations.AlterField(
            model_name="productbrand",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/brand/"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/category/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avt_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/user/"),
        ),
    ]
