# Generated by Django 4.2.16 on 2024-11-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_date_shipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_VNPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, default=8, null=True)),
                ('amount', models.FloatField(blank=True, default=8.0, null=True)),
                ('order_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('vnp_TransactionNo', models.CharField(blank=True, max_length=255, null=True)),
                ('vnp_ResponseCode', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='UserPayment',
        ),
    ]
