# Generated by Django 4.2.16 on 2024-11-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_payment_vnpay_remove_userpayment_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment_vnpay',
            name='order_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
